delimiter $$

CREATE TABLE `STUDENT` (
  `SNO` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  `TEL` varchar(20) NOT NULL,
  `ADDRESS` varchar(45) DEFAULT NULL,
  `AGE` int(11) DEFAULT '0',
  `WORKING` varchar(1) DEFAULT 'N',
  PRIMARY KEY (`SNO`),
  UNIQUE KEY `TEL_UNIQUE` (`TEL`)
) ENGINE=InnoDB AUTO_INCREMENT=97 DEFAULT CHARSET=utf8$$

